name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Connect to Docker 
      run: docker -H tcp://103.176.25.7:84 info
    - name: Connect check docker images 
      run: docker -H tcp://103.176.25.7:84 images
    - name: Connect check docker ps 
      run: docker -H tcp://103.176.25.7:84 ps
    # - name: Build the Docker image
    #   run: docker build -t hubertquang/hubert_repo:test_image_v1 WetherApi/.
    # - name: Log into Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    # - name: Push Docker image to Docker Hub
    #   run: docker push hubertquang/hubert_repo:test_image_v1
    
